### ISSUE TITLE
이슈

### ISSUE THREAD

**Issue by muzi55** [muzi55/muzimethod#11]
![제목 없음](https://github.com/muzi55/muzimethod/assets/132406946/65510969-82a1-4fcd-82ee-efcaf0607d49)

**Comment by muzi55** [comment]
db.json 보면 유저, 포스트, 코멘트가있는대
포스트안에 코멘트를 넣는게 더 적합한가여?
post {
 ... 여러가지
 comments: [
 ...여러가지
 ]
}  이런방식으로

development 환경에서만 redux devtool이 활성화 되도록 처리합니다.
이부분은 시도해봤는대 잘안됐던거같습니다 무얼 어캐해야하는지 감이안잡히네요

**Comment by muzi55** [comment]
https://muzimethod.vercel.app/?vercelToolbarCode=fn_SBvCRmwp3ccY
vercel 배포 완료했습니다 :D (자력으로)

**Comment by muzi55** [comment]
json 서버에 이미지 업로드 방법을 구성했습니다.
이제 json 서버에 이미지를 업로드 할 수 있습니다.!

**Comment by muzi55** [comment]
이미지를 하나씩밖에 업로드를 하지 못합니다. 이유는 무엇일까요

**Comment by yeongsbook** [comment]
> db.json 보면 유저, 포스트, 코멘트가있는대 포스트안에 코멘트를 넣는게 더 적합한가여?
> 
> ```
> post [
>  ... 여러가지
> comments: [
>  ... 여러가지
>  ]
> ]
> ```
> 
> 이런방식으로
> 
> development 환경에서만 redux devtool이 활성화 되도록 처리합니다. 이부분은 시도해봤는대 잘안됐던거같습니다 무얼 어캐해야하는지 감이안잡히네요

comments 배열로 따로 분리하는게 더 좋을 거 같아요. 댓글이 보통 텍스트뿐만 아니라 언제, 누가 작성했는지 등에 대한 정보를 가지고 있으며 수정과 삭제를 할 때도 comments가 따로 있는게 관리하기 쉬울 것 같습니다.

develop 환경에서만 redux devtool은 [링크](https://velog.io/@roses16-dev/React-Redux-Dev-Tools-Development-server%EC%97%90%EC%84%9C%EB%A7%8C-%EC%8B%A4%ED%96%89%EB%90%98%EA%B2%8C-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0) 참고해보세요.

**Comment by yeongsbook** [comment]
> json 서버에 이미지 업로드 방법을 구성했습니다. 이제 json 서버에 이미지를 업로드 할 수 있습니다.! multiple 속성으로 여러장의 이미지를 업로드 할 수 있습니다.
> 
> ![1200](https://user-images.githubusercontent.com/132406946/253684192-f3077932-f0a7-456f-8646-6cd9a9eeb23b.PNG)
> 
> 이미지를 업로드할때 너무 너무 무지무지무지무지~~~ 길어집니다. 이것에 대한 해결방법을 알고 싶습니다.

이미지나 파일들은 보통 스토리지에 저장해서 사용합니다. 위 방법처럼 이미지를 텍스트로 변환하여 DB에 저장하면 초기로딩속도가 많이 느려질 것 같습니다.
