### ISSUE TITLE
리액트 심화주차 레벨4 과제 피드백 - 오창영 튜터

### ISSUE THREAD

**Issue by yeongsbook** [muzi55/muzimethod#13]
배포 잘해주셨습니다.
.env는 중요한 정보가 담긴 파일입니다. .gitignore에 포함해주세요.
publie/index.html를 잘 수정해주셨습니다. lang="ko"와 `<meta name="description" content="BMI 계산기입니다" />`까지 수정해주시면 더 좋을 것 같습니다.
axios의 baseURL을 적용한 instance를 사용하시면 process.env.REACT_APP_SERVER_URL 반복을 줄일 수 있겠네요.

클래스가 중복되는 것을 방지하기 위해 컴포넌트별 scss는 module.scss 쓰시면 더 좋을 것 같습니다. 중복되지 않게 잘 구성하시면 필수는 아닙니다.

https://github.com/muzi55/muzimethod/blob/68a19238e92e91e7cea7858526ade4ea5c6e5ead/src/components/Header/Header.jsx#L21-L37
navigate("/")는 checkOr가 true일때만 실행되는 것으로 보입니다. 기능상으로는 차이가 없지만 31번째 줄로 이동하는게 더 파악하기 쉬운 코드가 될 것 같아요.

컴포넌트, 페이지에서 jsx, js가 혼용되어 사용되고 있습니다. 하나로 통일해주세요.

https://github.com/muzi55/muzimethod/blob/68a19238e92e91e7cea7858526ade4ea5c6e5ead/src/pages/Join/Join.jsx#L57
하드코딩된 문자열 비교보다는 const로 선언하여 사용하시는 걸 추천드립니다. 휴먼에러방지를 위해서입니다.
```
as-is
case "name":

to-be
const NAME = "NAME"
case NAME:

<input ... name={NAME} ... />
```

이슈로 질문주신 내용은 피드백 시간이 부족하여 확인해보고 다시 남기겠습니다.
과제하시느라 고생많으셨습니다!

**Comment by muzi55** [comment]
감사합니다 !
